# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import glob
import os

#get all the build variables we need
Import('env', 'project', 'buildroot')
env = env.Clone()

# get sub-SConscripts
subscripts = glob.glob('*/SConscript')

# set library path
oldisim_lib_path = buildroot + '/oldisim'

# set new buildroot
buildroot = buildroot + '/workloads'

for script in subscripts:
  project = os.path.dirname(script)
  SConscript(script, exports = ['env', 'buildroot', 'project', 'oldisim_lib_path'])
